name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  CD:
#    needs: [CI]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Connect Tailscale
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_KEY }} 
          version: 1.14.0      
            
      
      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG_PI }}

      - name: Trigger deploy
        uses: phamquyhai/kubernetes-action@master
        with:
          args: apply -k pv./kustomization.yaml

#      - name: Deploy to Kubernetes cluster
#        uses: Azure/k8s-deploy@v1.5
#        with:
#          images: wordpress:4.8-apache
#          manifests: |
#            pv/mysql-deployment.yaml
#            pv/wordpress-deployment.yaml
            

#      - name: 'Kustomize Build'
#        uses: karancode/kustomize-github-action@master
#        with:
#          kustomize_version: '3.0.0'
#          kustomize_build_dir: '.'
#          kustomize_comment: true
#          kustomize_output_file: "pv/kustomization.yaml" #gitops/rendered.yaml
#          kustomize_build_options: "--load_restrictor none"
#          enable_alpha_plugins: true
#        env:
#          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
